# Generated by Django 5.2.6 on 2025-11-03 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitrecord',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='habitrecord',
            constraint=models.UniqueConstraint(fields=('habit', 'date', 'user'), name='unique_habit_per_day'),
        ),
    ]
