# Generated by Django 5.2.6 on 2025-10-18 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='habitrecord',
            name='progress',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='habitrecord',
            unique_together={('habit', 'date')},
        ),
    ]
