# Generated by Django 5.2.6 on 2025-09-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='category',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='habit',
            name='habits_habi_user_id_6741d6_idx',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='skip_allowed',
        ),
        migrations.RemoveField(
            model_name='habitrecord',
            name='updated_at',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
