# Generated by Django 5.2.6 on 2025-10-09 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_updated_at_category_habit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='#0003A3', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habits', to='habits.category'),
        ),
    ]
