# Generated by Django 5.2.6 on 2025-11-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habitrecord_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
