# Generated by Django 5.2.6 on 2026-08-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_progress_created_at_progress_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitrecord',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
